### ISSUE TITLE
Game Crashes when command used 

### ISSUE THREAD

**Issue by aquahonoredhi** [NotRyken/ClaimPoints#1]
In version 1.20.4 with Xaero Minimap versions 24.0.1 and newer, with Claim Points version 0.1.0-alpha.01, whenever one of the commands adding/removing waypoints is run, the game crashes. 

Game Log: [](https://mclo.gs/MNhrokb)
Mods: 
Xaero Minimap 24.0.1 OR 24.0.2
Fabric API 0.96.11+1.20.4
Claim Points 0.1.0-alpha.01

**Comment by NotRyken** [comment]
Thanks for opening this issue.

You haven't actually included a game log, though in this case it doesn't matter since the issue is easily reproducible. Per the [Xaero's Minimap changelog](https://chocolateminecraft.com/update.php?mod_id=0), 24.0.1 breaks compatibility with most integrations, ClaimPoints included. You can expect an update to be rolled out sometime in the next two or three days.

**Comment by NotRyken** [comment]
Latest alpha on [Modrinth](https://modrinth.com/mod/claimpoints/versions) is now compatible with XM 24.0.x
